language: c
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=mitchellsalad
    - secure: "cqOim8ooCXPCg1qr8dO2XVzg40PKeQuMz2gjJAsmwikcE+AogZ0FYD3SwP6j3fxPi5iNndB9ykDncqgGL/XSYiPadF6YiSkFTYpXkZRLpZcliWSBDqH07ZQgwni1ay7heqVCM8+IubbInnfy5feyPSBlIHzLD8buDxaggSqZRtRGRQ6ExTxrEqD3blrSyYDUjnWyZaOwT5tx3fqV4GFVQbJqD35K3kRS+wrMMXvsM07RSYaSzJFBNVuoZkW1hIAl5FOMreFLCnNPjsY5DBWRB/QAnlXP7Rzj9fXib2/O704w6PRzV6EeteFbs8vDdvhUdxpwt/htAYnLpMMFe0qmnfoQhjbAoGv682hk+ovYgwLwF7hOqM5yQiFXQk+A5oDcUBwH2Wbb1DskWvL2f72OjLyYToBxa0mInPDD+Q2GiRo8q0Z/Qnrx3ImNWagirzMg5d7yHPyLdSB35b2/TGIrHUWmOyP2BD2b3n0IK0CENLzQLAw4GBLiCaxB/nL95HwvMhP0OEgy0HSH1k92zUPMWYqH+s1qlsVqIBHEzRJDFa5jh45PAWgpxJJSuvYp6CzC775z5qL05oSFlXiZ36DPc4TcnzOhnaQX5NVtVc+vmwFcKfSTYYzVBGQT5hHfFkGQLLr0Gz0t0GHPvs5cUo/PUZAVHBPy5Y6EJI+Yuw44Sxk="

# Notify the 'snowdrift-control' server on successful build.
notifications:
  webhooks: http://45.33.68.74:8001/
  on_success: always
  on_failure: never
  on_start: never
  on_cancel: never
  on_error: never

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull mitchellsalad/ghc-8.2.2:latest
  - docker pull phusion/baseimage:0.10.1
  - mkdir -p dist

install:
  - docker run --detach --tty --name snowdrift --env SNOWDRIFT_VERSION=$TRAVIS_COMMIT --mount "type=bind,src=$HOME/.cabal,dst=/root/.cabal" --mount "type=bind,src=$PWD,dst=/snowdrift" mitchellsalad/ghc-8.2.2
  - docker exec snowdrift sh -c "cd snowdrift && HOME=/root cabal new-update"
  - docker exec snowdrift sh -c "cd snowdrift && HOME=/root cabal new-build --disable-tests --disable-benchmarks --only-dependencies -j2 all"

script:
  - docker exec snowdrift sh -c "cd snowdrift && HOME=/root cabal new-build --enable-tests --enable-benchmarks -j2 all"
  - docker exec snowdrift sh -c "cd snowdrift && cp \$(find dist-newstyle/ -name snowdrift -type f -executable) dist/"
  - docker exec snowdrift sh -c "cd snowdrift && cp \$(find dist-newstyle/ -name snowdrift-control -type f -executable) dist/"
  - docker build . -f deploy/DeployDockerfile -t mitchellsalad/snowdrift
  - docker push mitchellsalad/snowdrift
